const CLASSES_SUCCESS = 'CLASSES_SUCCESS';
const CLASSES_FAILURE = 'CLASSES_FAILURE';
const CLASSES_REQUEST = 'CLASSES_REQUEST';
const types = {
    CLASSES_REQUEST,
  CLASSES_SUCCESS,
  CLASSES_FAILURE,
};
export default types;
