const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
const types = {
    NOTIFICATION_REQUEST,
    NOTIFICATION_SUCCESS,
    NOTIFICATION_FAILURE,
};
export default types;
