const SUBJECTS_SUCCESS = 'SUBJECTS_SUCCESS';
const SUBJECTS_FAILURE = 'SUBJECTS_FAILURE';
const SUBJECTS_REQUEST = 'SUBJECTS_REQUEST';
const types = {
    SUBJECTS_REQUEST,
    SUBJECTS_SUCCESS,
    SUBJECTS_FAILURE,
};
export default types;
