const TEACHERS_SUBMIT_SUCCESS = 'TEACHERS_SUBMIT_SUCCESS';
const TEACHERS_SUBMIT_FAILURE = 'TEACHERS_SUBMIT_FAILURE';
const TEACHERS_SUBMIT_REQUEST = 'TEACHERS_SUBMIT_REQUEST';
const types = {
    TEACHERS_SUBMIT_REQUEST,
    TEACHERS_SUBMIT_FAILURE,
    TEACHERS_SUBMIT_SUCCESS,
};
export default types;
